const size = {
    mobile: '320px',
    tablet: '768px',
    laptop: '1024px',
  }

export const device = {
    mobile: `(min-width: ${size.mobile})`,
    tablet: `(min-width: ${size.tablet})`,
    laptop: `(min-width: ${size.laptop})`,
  };

export const phoneCodes = ["", "93", "355", "213", "684", "376", "244", "264", "268", "54", "374", 
                            "297", "61", "672", "43", "994", "242", "973", "880", "246", "375", "32", 
                            "501", "229", "441", "975", "591", "387", "267", "55", "284", "673", "359", 
                            "226", "257", "855", "237", "238", "345", "236", "235", "56", "86", "57",
                            "269", "243", "242", "682", "506", "385", "53", "357", "420", "45", "246",
                            "253", "767", "809", "593", "20", "503", "240", "291", "372", "251", "500", 
                            "298", "679", "358", "33", "594", "241", "220", "995", "49", "233", "350", 
                            "30", "299", "473", "590", "502", "44", "224", "245", "592", "509", "504", 
                            "852", "36", "354", "91", "62", "98", "964", "353", "44", "972", "39", "255", 
                            "876", "81", "44", "962", "7", "254", "686", "850", "82", "965", "996", "856", 
                            "371", "961", "266", "231", "218", "423", "370", "352", "853", "389", "261", 
                            "265", "60", "960", "223", "356", "692", "596", "222", "230", "52", "691", 
                            "373", "377", "976", "382", "664", "212", "258", "95",'264', "674", "977", 
                            "31", "599", "687", "64", "505", "227", "234", "670", "47", "968", "64", "505", 
                            "227", "234", "670", "47", "968", "92", "680", "970", "507", "675", "595", "51", 
                            "63", "48", "351", "974", "262", "40", "7", "250", "685", "378", "239", "966", 
                            "221", "281", "248", "232", "65", "721", "421", "386", "677", "27", "211", "34", 
                            "94", "508", "869", "758", "784", "249", "597", "46", "41", "963", "886", "992", 
                            "66", "228", "690", "676", "868", "216", "90", "993", "649", "688", "256", "380", 
                            "971", "598", "998", "678", "58", "84", "967", "260", "263"];

export const titles = [
    {
        id: 1,
        text: "INFORMACION PERSONAL",
        name: "informacional_personal",
        col_start: 1,
        col_end: 7,
        row_start: 1,
        row_end: 1,
        order:0,
    },
    {
        id: 2,
        text: "INFORMACION DE TARJETA DE CREDITO/DEBITO",
        name: "informacion_de_tarjeta",
        col_start: 1,
        col_end: 7,
        row_start: 8,
        row_end: 8,
        order:10,
    },
    {
        id: 3,
        text: "INFORMACION DE EMERGENCIA",
        name: "informacion_de_emergencia",
        col_start: 1,
        col_end: 7,
        row_start: 10,
        row_end: 10,
        order:16
    }
]

export const phones = [
    {
        id: 4,
        label_text:'Numero de telefono',
        input_placeholder:'00000000',
        name: "numero_de_telefono_personal",
        type:'text',
        isOptional: false,
        pattern: "[0-9]{8}",
        errorMessage: "Su numero de telefono no puede tener letras, solo numero, y debe tener minimo 8 caracteres. No olvide agregar su codigo del pais",
        col_start: 1, 
        col_end: 4,
        row_start: 5,
        row_end: 5,
        order: 7
    },
    {
        id: 5,
        label_text:'Numero de casa',
        input_placeholder:'00000000',
        name: "numero_telefono_casa_personal",
        type:'text',
        isOptional: true,
        pattern: "[0-9]{8}",
        errorMessage: "Su numero de telefono no puede tener letras, solo numero, y debe tener minimo 8 caracteres. No olvide agregar su codigo del pais",
        col_start: 4, 
        col_end: 7,
        row_start: 5,
        row_end: 5,
        order: 8,
    },
    {
        id: 6,
        label_text:'Numero de telefono',
        input_placeholder:'00000000',
        name: "numero_telefono_emergencia",
        type:'text',
        isOptional: true,
        pattern: "[0-9]{8}",
        errorMessage: "Su numero de telefono no puede tener letras, solo numero, y debe tener minimo 8 caracteres. No olvide agregar su codigo del pais",
        col_start: 1, 
        col_end: 4,
        row_start: 14,
        row_end: 14,
        order:23
    },
    {
        id: 7,
        label_text:'Numero de casa',
        input_placeholder:'00000000',
        type:'text',
        name: "numero_telefono_casa_emergencia",
        isOptional: true,
        pattern: "[0-9]{8}",
        errorMessage: "Su numero de telefono no puede tener letras, solo numero, y debe tener minimo 8 caracteres. No olvide agregar su codigo del pais",
        col_start: 4, 
        col_end: 7,
        row_start: 14,
        row_end: 14,
        order:24
    }

] 

export const fieldsets = [
    {
        id: 8,
        label_text:'Primer nombre',
        input_placeholder:'Primer nombre',
        type:'text',
        name: "primer_nombre",
        isOptional: false,
        pattern: "[A-Za-z]{1,32}",
        errorMessage: "Su nombre debe poseer solo letras",
        col_start: 1, 
        col_end: 4,
        row_start: 2,
        row_end: 2,
        order:1,
    },
    {
        id: 9,
        label_text:'Segundo nombre',
        input_placeholder:'Segundo nombre',
        type:'text',
        name: "segundo_nombre",
        isOptional: false,
        pattern: "[A-Za-z]{1,32}",
        errorMessage: "Su nombre debe poseer solo letras",
        col_start: 4, 
        col_end: 7,
        row_start: 2,
        row_end: 2,
        order: 2,
    },
    {
        id: 10,
        label_text:'Primer apellido',
        input_placeholder:'Primer apellido',
        type:'text',
        name: "primer_apellido",
        isOptional: false,
        pattern: "[A-Za-z]{1,32}",
        errorMessage: "Su apellido debe poseer solo letras",
        col_start: 1, 
        col_end: 4,
        row_start: 3,
        row_end: 3,
        order: 3
    },
    {
        id: 11,
        label_text:'Segundo apellido',
        input_placeholder:'Segundo apellido',
        type:'text',
        name: "segundo_apellido",
        isOptional: false,
        pattern: "[A-Za-z]{1,32}",
        errorMessage: "Su apellido debe poseer solo letras",
        col_start: 4, 
        col_end: 7,
        row_start: 3,
        row_end: 3,
        order: 4,
    },
    {
        id: 12,
        label_text:'Fecha de nacimiento',
        input_placeholder:'-- / ----',
        type:'date',
        name: "fecha_de_nacimiento",
        isOptional: false,
        pattern: "",
        errorMessage: "",
        col_start: 1, 
        col_end: 3,
        row_start: 4,
        row_end: 4,
        order:5,
    },
    {
        id: 13,
        label_text:'Email',
        input_placeholder:'ejemplo@gmail.com',
        type:'email',
        name: "email",
        isOptional: false,
        pattern: "[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$",
        errorMessage: "El formato de su correo debe ser parecido al siguiente ejemplo: luis@gmail.com",
        col_start: 3, 
        col_end: 7,
        row_start: 4,
        row_end: 4,
        order:6,
    },
    {
        id: 14,
        label_text:'Direccion',
        input_placeholder:'',
        type:'text',
        name: "direccion",
        isOptional: false,
        pattern: "([a-zA-Z0-9]| |/|.|)+",
        errorMessage: "Su direccion solo puede poseer letras mayusculas, minusculas, numeros, espacios, punto(.), diagonal(/) y espacios en blanco. No se permite caracteres especiales de otro tipo",
        col_start: 1, 
        col_end: 7,
        row_start: 7,
        row_end: 7,
        order:9
    },
    {
        id: 15,
        label_text:'Numero de identificacion',
        input_placeholder:'0000000000000',
        type:'text',
        name: "numero_de_identificacion",
        isOptional: false,
        pattern: "[0-9]{13,16}",
        errorMessage: "Su numero de identificacion solo puede poseer numero y tener entre 13 a 16 caracteres",
        col_start: 1, 
        col_end: 4,
        row_start: 6,
        row_end: 6,
        order:11,
    },
    {
        id: 16,
        label_text:'Numero de Pasaporte',
        input_placeholder:'0000000000000',
        type:'text',
        name: "numero_pasaporte",
        isOptional: false,
        pattern: "[0-9]{9}",
        errorMessage: "Su numero de identificacion solo puede poseer numeros y un minimo de 9 caracteres",
        col_start: 4, 
        col_end: 7,
        row_start: 6,
        row_end: 6,
        order: 12
    },
    {
        id: 17,
        label_text:'Tarjeta de Credito/Debito',
        input_placeholder:'0000000000000000',
        type:'text',
        name: "tajeta_bancaria",
        isOptional: false,
        pattern: "[0-9]{12}",
        errorMessage: "la numeracion de su tarjeta de credito o debito no puede poseer letras, solo numeros, y debe tener 12 caracteres",
        col_start: 1, 
        col_end: 4,
        row_start: 9,
        row_end: 9,
        order:13,
    },
    {
        id: 18,
        label_text:'Fecha de vencimiento',
        input_placeholder:'-- / ----',
        type:'month',
        name: "fecha de vencimiento",
        isOptional: false,
        pattern: "",
        errorMessage: "",
        col_start: 5, 
        col_end: 7,
        row_start: 9,
        row_end: 9,
        order:14,
    },
    {
        id: 19,
        label_text:'CVC',
        input_placeholder:'---',
        type:'text',
        name: "cvc",
        isOptional: false,
        pattern: "[0-9]{3}",
        errorMessage: "Su codigo CVC al reverso de su tarjeta debe de ser solo numeros y minimo 3 caracteres",
        col_start: 4, 
        col_end: 5,
        row_start: 9,
        row_end: 9,
        order:15,
    },
    {
        id: 20,
        label_text:'Primer nombre',
        input_placeholder:'Primer nombre',
        type:'text',
        name: "primer_nombre_opcional",
        isOptional: true,
        pattern: "[A-Za-z]{1,32}",
        errorMessage: "Su nombre debe poseer solo letras",
        col_start: 1, 
        col_end: 4,
        row_start: 11,
        row_end: 11,
        order:17
    },
    {
        id: 21,
        label_text:'Segundo nombre',
        input_placeholder:'Segundo nombre',
        type:'text',
        name: "segundo_nombre_opcional",
        isOptional: true,
        pattern: "[A-Za-z]{1,32}",
        errorMessage: "Su nombre debe poseer solo letras",
        col_start: 4, 
        col_end: 7,
        row_start: 11,
        row_end: 11,
        order:18
    },
    {
        id: 22,
        label_text:'Primer apellido',
        input_placeholder:'Primer apellido',
        type:'text',
        name: "primer_apellido_opcional",
        isOptional: true,
        pattern: "[A-Za-z]{1,32}",
        errorMessage: "Su apellido debe poseer solo letras",
        col_start: 1, 
        col_end: 4,
        row_start: 12,
        row_end: 12,
        order:19
    },
    {
        id: 23,
        label_text:'Segundo apellido',
        input_placeholder:'Segundo apellido',
        type:'text',
        name: "segundo_apellido_opcional",
        isOptional: true,
        pattern: "[A-Za-z]{1,32}",
        errorMessage: "Su apellido debe poseer solo letras",
        col_start: 4, 
        col_end: 7,
        row_start: 12,
        row_end: 12,
        order: 20
    },
    {
        id: 24,
        label_text:'Fecha de nacimiento',
        input_placeholder:'-- / ----',
        type:'date',
        name: "fecha_de_nacimiento_opcional",
        isOptional: true,
        pattern: "",
        errorMessage: "",
        col_start: 1, 
        col_end: 3,
        row_start: 13,
        row_end: 13,
        order:21
    },
    {
        id: 25,
        label_text:'Email',
        input_placeholder:'ejemplo@gmail.com',
        type:'email',
        name: "email_opcional",
        isOptional: true,
        pattern: "[a-z0-9._%+-]+@[a-z0-9.-]+\.[a-z]{2,}$",
        errorMessage: "El formato de su correo debe ser parecido al siguiente ejemplo: luis@gmail.com",
        col_start: 3, 
        col_end: 7,
        row_start: 13,
        row_end: 13,
        order: 22
    },
    {
        id: 26,
        label_text:'Direccion',
        input_placeholder:'',
        type:'text',
        name: "direccion_opcional",
        isOptional: true,
        pattern: "([a-zA-Z0-9]| |/|.|)+",
        errorMessage: "Su direccion solo puede poseer letras mayusculas, minusculas, numeros, espacios, punto(.), diagonal(/) y espacios en blanco. No se permite caracteres especiales de otro tipo",
        col_start: 1, 
        col_end: 7,
        row_start: 15,
        row_end: 15,
        order:25
    },
]